### ISSUE TITLE
Mouse movement/scrolling is slow

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#28]
This does actually happen to me too. Just putting it out there for possible considerations of improvement.

https://forums.cncnet.org/index.php?topic=7005.0;topicseen

**Comment by Rampastring** [comment]
Improved in https://github.com/CnCNet/xna-cncnet-client/commit/a1dc10fad42c92009870e1de6e4a49b28bb78587 and https://github.com/CnCNet/xna-cncnet-client/commit/378b984e70e7150616180731cd1267c40708faac

To apply the fix for YR, create a "cursor.cur" file in the Resources\ directory. The file MUST be in the Windows .cur cursor format, a regular image file won't do. This replaces the client's sprite-based cursor with the Windows hardware cursor, which removes all mouse lag.

I also lowered the client's FPS to 60 from 120, which should cut the CPU use in half on most systems.
