### ISSUE TITLE
Could not find required child control: PlayerOptionsPanel

### ISSUE THREAD

**Issue by sovzzz** [CnCNet/xna-cncnet-client#342]
Here is the crash log

[ClientCrashLog_2022_06_14_02_36.txt](https://github.com/CnCNet/xna-cncnet-client/files/8893624/ClientCrashLog_2022_06_14_02_36.txt)

What did I do:
1. Compile .exe files (Ares release x64)
2. Copy files from "Compiled" folder to DXMainClient\Resources.
3. Crash and noticed no "CliantUpdater.dll", so, copy .dll files from DXMainClient\bin\WindowsGL\Release
4. Crash again, and got log above

**Comment by sovzzz** [comment]
Is this a Bug or a configuration mistake? It didn't report an Error on compiling.

**Comment by sovzzz** [comment]
It seems to be caused by develop branch's difference. The sentence below exists in master but not in develop
`PlayerOptionsPanel = new XNAPanel(WindowManager);`
(209 line, xna-cncnet-client/DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs)
Does anyone else met this problem?

**Comment by devo1929** [comment]
That's a configuration problem. You've likely got misconfigured INI files. The line you mentioned is no longer necessary and intentionally not in the develop branch.

The specific line that is causing the crash is:
`GameLobbyBase.cs` line 204
where it says:
`PlayerOptionsPanel = FindChild<XNAPanel>(nameof(PlayerOptionsPanel));`

`PlayerOptionsPanel` is currently referenced in the YR `MultiplayerGameLobby.ini` file like this:
![image](https://user-images.githubusercontent.com/2062360/180622675-1f9a62fa-4263-48a5-a34c-91768ff8e80c.png)

**Comment by pzhlkj6612** [comment]
I've encountered the same problem. Thank you for the explanation, @devo1929 !

<br>

> That's a configuration problem. You've likely got misconfigured INI files. The line you mentioned is no longer necessary and intentionally not in the develop branch.
> 
> ...
> 
> `PlayerOptionsPanel` is currently referenced in the YR `MultiplayerGameLobby.ini` file like this: ...

Since you mentioned "YR", I copied the entire "Resources" directory of CnCNet/cncnet-yr-client-package@f7c11eccf6ea887b3c9774171a4f5590f3ea5b69 to the build output directory and the client works fine.

<br>

However, the [README](https://github.com/CnCNet/xna-cncnet-client/blob/2c7f7a1862d33d191dd4b3bb21e1debbf360a652/README.md) said:

> Compiling, debugging and usage
> ------------------------------
> 
> * Compiling itself is simple: ...
> * When built as a debug build, the client executable expects to reside in the same directory with the target project's main game executable. Resources should exist in a "Resources" sub-directory in the same directory. The repository contains sample resources and post-build commands for copying them so that you can immediately run the client in debug mode by just hitting the Debug button in Visual Studio.

We do have a sample "[MultiplayerGameLobby.ini](https://github.com/CnCNet/xna-cncnet-client/blob/2c7f7a1862d33d191dd4b3bb21e1debbf360a652/DXMainClient/Resources/DTA/MultiplayerGameLobby.ini)" file, but it does not contain the up-to-date content (_Latest commit 6861c659ef7fe02039909d1f81fc5b3438f7fd95 on Jun 30, 2016_). Maybe we can update these files to match the new codebase, by referring to the "_INI changes for v6 client changes_" commit (CnCNet/cncnet-yr-client-package@3cc4422a8c5bd29476803ae2ddff779afa78a782).

**Comment by alexlambson** [comment]
I am encountering the same issue after rebasing from develop. My ini file doesn't look like the screenshot.
