### ISSUE TITLE
Creating new windows

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#43]
So I'm working on integrating accounts, I've got to this so far with authentication: https://drive.google.com/file/d/0B5eSYrI0mFL2RnZJZjd2eTRfeXc/view

It's a work in progress, communicating with the API here - https://github.com/CnCNet/ladder-api

The UI handling could be better so I'm thinking it should move away from `CnCNetLoginWindow` and just have a button that opens up a new window that's Account management or similar. 

What's the best way of creating a new window (Something similar to the PM message/ Friend list view)?

**Comment by Rampastring** [comment]
Create a new class for the new window (you have plenty of examples of this), create an instance of that class (it's best to keep just one instance of the window that's alive through the entire client session), and then either add that window as a child of another control or add the window to the WindowManager as a control (I'd take this approach). When you want to show your new window, just call Enable() on a reference of the window.

If you also want to darken the background of the window (which'd be good for consistency), use DarkeningPanel.AddAndInitializeWithControl. For an example of this, see https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/DXGUI/Generic/LoadingScreen.cs#L124

In this case I wouldn't use the LoadingScreen for adding the window, however; since you want to access the window by clicking on a button in CnCNetLoginWindow, I'd create and initialize the new window (with DarkeningPanel.AddAndInitializeControl) in CnCNetLoginWindow.Initialize(). Then when the user presses the button, simply call Enable() on the window control.

I could come to the CnCNet IRC to discuss this on the weekend if you need more pointers.
