### ISSUE TITLE
Why are all the servers in China gone?

### ISSUE THREAD

**Issue by 285984303** [CnCNet/xna-cncnet-client#477]
Why are all the servers in China gone?

**Comment by SadPencil** [comment]
Please just stop asking questions in just one sentence. You need to learn how to properly determine whether a problem is widely repeatable or not and also who is to blame. Learn _How To Ask Questions The Smart Way_ (《提问的智慧》) first. Also, speaking to this networking issue, you are suppose to know what "Cloudflare" and "GFW" are before submitting your issue here.

**Comment by Metadorius** [comment]
Additionally, if you continue asking unrelated questions, not following what @SadPencil told you in this and another issues etc. we are going to limit your repository access. This is an issue tracker, not a Q&A.
