### ISSUE TITLE
Adding new libraries 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#53]
I think I've got it but just need to confirm. I've made a new project called CnCNetServices which has a bunch of binaries required including its own called CnCNetServices.dll

Now when it comes to release, am I adding CnCNetServices to SPECIFIC_LIBRARIES? What happens to the binaries needed for CnCNetServices and how does the main client read them?

![binaries](https://cloud.githubusercontent.com/assets/6104940/26544699/99af0b38-445a-11e7-8c95-7b71a3e30138.png)

**Comment by Rampastring** [comment]
SPECIFIC_LIBRARIES contains only libraries that need MonoGame / XNA in some way. Since CnCNetServices does not do that, you should add it to COMMON_LIBRARIES instead, and then it'll be read from the root of Resources\Binaries\.

Unless I'm mistaken, some of those DLLs (all Microsoft* and System* DLLs) look like DLLs that are already included in .NET Framework, and so you don't need to include them. As for Newtonsoft.Json.dll, add it to COMMON_LIBRARIES as well and the client will also read it from Resources\Binaries\.
