### ISSUE TITLE
File Hashes and Comparison Message

### ISSUE THREAD

**Issue by CnCRAZER** [CnCNet/xna-cncnet-client#572]
Currently when joining a lobby the client tells you about different gamefiles etc etc blah blah blah. 

This is useful, but also kind of hard for some users to pinpoint if something is accidently changed. They most likely don't know which file to go back and change / edit back to default values. 

IMO, what should happen, is the message should go something like this: "Player 'RAZER' has a modified 'xyz-example-file-name' compared to the game host. Player 'RAZER' may or may not be trying to cheat." 

![image](https://github.com/user-attachments/assets/3eb9b07a-e50f-4c2e-8f1c-7e919d77bf45)

**Comment by SadPencil** [comment]
Currently, the client only sends a single hash that identifies whether any files has changed or not in order to save the traffic usage. It should consume a lot of network traffic to identify which specific file has been modified and thus I don't think this feature will be implemented for a relatively long period.

**Comment by CnCRAZER** [comment]
@SadPencil All good.  Maybe in the future it can be deemed worthy but was just a random idea.
