### ISSUE TITLE
Updater does not close the Client and hangs

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#84]
This is just one case: https://forums.cncnet.org/topic/9246-dta-client-update-waiting-forever/
But this is a thing I keep hearing and seeing. 

It doesn't happen to everyone, just some users. The only way they are able to resolve this is by closing the DTA client manually via task manager, and then the update proceeds.

**Comment by Rampastring** [comment]
I don't personally encounter the bug, but @dkeetonx got it on some Windows system a few days ago. He did some debugging and found out that only the MonoGame DirectX version (`clientdx.exe`) of the client fails to close itself; with the XNA and OpenGL versions updating works properly. This would point towards it being a bug in the DX11 build of MonoGame where it fails at releasing some resources on shutdown on some systems and then hangs.

As a workaround we could just probably call `Environment.Exit()` when the client is supposed to exit instead of only calling `Game.Exit()` (through `Rampastring.XNAUI.WindowManager.CloseGame()`) and relying on MonoGame to handle the shutdown for us. I'll implement this soon.
